# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-22 11:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacturaAnulada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nro_factura', models.CharField(default='002-001-', max_length=50, unique=True, verbose_name='Nro de Factura')),
                ('fecha_factura', models.DateField(default=django.utils.timezone.now)),
                ('tipo_factura', models.IntegerField(choices=[(1, 'Contado'), (2, 'Credito')], default=1)),
                ('total_vendido', models.IntegerField(default=0)),
                ('monto_total', models.IntegerField(default=0, verbose_name='Monto')),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.Cliente')),
            ],
            options={
                'ordering': ['-fecha_factura', 'cliente'],
                'verbose_name': 'Factura Anulada',
                'verbose_name_plural': 'Facturas Anuladas',
            },
        ),
        migrations.CreateModel(
            name='FacturaAnuladaMercaderia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(default=0)),
                ('precio_unitario', models.IntegerField(default=0)),
                ('facturaanulada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facturas.FacturaAnulada')),
            ],
        ),
        migrations.CreateModel(
            name='FacturaCompra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nro_factura', models.CharField(max_length=50, unique=True, verbose_name='Nro de Factura')),
                ('fecha_factura', models.DateField(default=django.utils.timezone.now)),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('monto', models.IntegerField(blank=True, default=0, verbose_name='Monto Total')),
            ],
            options={
                'verbose_name': 'Factura de Compra',
                'verbose_name_plural': 'Facturas de Compra',
            },
        ),
        migrations.CreateModel(
            name='FacturaCompraGasto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(default=0)),
                ('obs', models.CharField(blank=True, max_length=30, null=True)),
                ('precio_unitario', models.IntegerField(default=0, verbose_name='Precio Unitario')),
                ('facturacompra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facturas.FacturaCompra')),
            ],
        ),
        migrations.CreateModel(
            name='FacturaVenta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nro_factura', models.CharField(default='002-001-', max_length=50, unique=True, verbose_name='Nro de Factura')),
                ('fecha_factura', models.DateField(default=django.utils.timezone.now)),
                ('tipo_factura', models.IntegerField(choices=[(1, 'Contado'), (2, 'Credito')], default=1)),
                ('total_vendido', models.IntegerField(default=0)),
                ('monto_total', models.IntegerField(default=0, verbose_name='Monto')),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('saldo', models.IntegerField(default=0)),
                ('cancelado', models.BooleanField(default=True)),
                ('fecha_cancelacion', models.DateField(blank=True, help_text='la fecha en cuestion es la fecha del utlimo recibo de cancelacion.', null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.Cliente')),
                ('delivery', models.ForeignKey(help_text='Vendedor que ejecuto el reparto.', on_delete=django.db.models.deletion.CASCADE, to='clientes.Vendedor')),
            ],
            options={
                'ordering': ['-fecha_factura', 'cliente'],
                'verbose_name': 'Factura de Venta',
                'verbose_name_plural': 'Facturas de Venta',
            },
        ),
        migrations.CreateModel(
            name='FacturaVentaMercaderia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(default=0)),
                ('precio_unitario', models.IntegerField(default=0)),
                ('facturaventa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facturas.FacturaVenta')),
            ],
        ),
        migrations.CreateModel(
            name='Gasto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concepto', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Concepto',
                'verbose_name_plural': 'Conceptos',
            },
        ),
        migrations.CreateModel(
            name='Mercaderia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('cantidad', models.IntegerField(default=0, help_text='cantidad de barritas contenidas en una caja')),
                ('costo', models.IntegerField(default=0, help_text='costo una barrita (individual)')),
            ],
        ),
        migrations.CreateModel(
            name='Recibo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_recibo', models.DateTimeField(verbose_name='Fecha de recibo')),
                ('nro_recibo', models.CharField(max_length=20)),
                ('monto', models.IntegerField(default=0)),
                ('facturaventa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facturas.FacturaVenta')),
            ],
        ),
        migrations.CreateModel(
            name='Reposicion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_reposicion', models.DateField(default=django.utils.timezone.now)),
                ('monto', models.IntegerField(default=0)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.Cliente')),
                ('delivery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.Vendedor')),
            ],
            options={
                'verbose_name': 'Reposicion',
                'verbose_name_plural': 'Reposiciones',
            },
        ),
        migrations.CreateModel(
            name='ReposicionMercaderia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('mercaderia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facturas.Mercaderia')),
                ('reposicion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facturas.Reposicion')),
            ],
        ),
        migrations.AddField(
            model_name='reposicion',
            name='mercaderias',
            field=models.ManyToManyField(through='facturas.ReposicionMercaderia', to='facturas.Mercaderia'),
        ),
        migrations.AddField(
            model_name='facturaventamercaderia',
            name='mercaderia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facturas.Mercaderia'),
        ),
        migrations.AddField(
            model_name='facturaventa',
            name='mercaderias',
            field=models.ManyToManyField(through='facturas.FacturaVentaMercaderia', to='facturas.Mercaderia'),
        ),
        migrations.AddField(
            model_name='facturacompragasto',
            name='gasto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facturas.Gasto'),
        ),
        migrations.AddField(
            model_name='facturacompra',
            name='concepto',
            field=models.ManyToManyField(through='facturas.FacturaCompraGasto', to='facturas.Gasto'),
        ),
        migrations.AddField(
            model_name='facturacompra',
            name='proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.Proveedor'),
        ),
        migrations.AddField(
            model_name='facturaanuladamercaderia',
            name='mercaderia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facturas.Mercaderia'),
        ),
        migrations.AddField(
            model_name='facturaanulada',
            name='mercaderias',
            field=models.ManyToManyField(through='facturas.FacturaAnuladaMercaderia', to='facturas.Mercaderia'),
        ),
        migrations.AddField(
            model_name='facturaanulada',
            name='vendedor',
            field=models.ForeignKey(help_text='Vendedor al cual pertenece la factura anulada.', null=True, on_delete=django.db.models.deletion.CASCADE, to='clientes.Vendedor'),
        ),
        migrations.AlterUniqueTogether(
            name='facturaventamercaderia',
            unique_together=set([('facturaventa', 'mercaderia')]),
        ),
        migrations.AlterUniqueTogether(
            name='facturacompragasto',
            unique_together=set([('facturacompra', 'gasto')]),
        ),
        migrations.AlterUniqueTogether(
            name='facturaanuladamercaderia',
            unique_together=set([('facturaanulada', 'mercaderia')]),
        ),
    ]
