# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-28 12:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recibo',
            name='fecha_recibo',
            field=models.DateField(verbose_name='Fecha de recibo'),
        ),
    ]
