# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-19 07:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controlhorario',
            name='horario_entrada',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='controlhorario',
            name='horario_salida',
            field=models.TimeField(blank=True),
        ),
    ]
