# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-19 07:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0002_auto_20160419_0704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controlhorario',
            name='horario_salida',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
